server:
  port: 10002
spring:
  application:
    name: gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: 875814854
    database: 2
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:10001/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2